In [2]:
import pandas as pd 
df = pd.read_csv("data/employment_by_sex.csv")
df.head()

,DATAFLOW,LAST UPDATE,freq,indic_em,unit,age,sex,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Austria,2009,68.2,NaN,NaN
1,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Austria,2010,68.8,NaN,NaN
2,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Austria,2011,69.2,NaN,NaN
3,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Austria,2012,69.6,NaN,NaN
4,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Austria,2013,70.0,NaN,NaN

In [3]:
df.shape

(1896, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1896 entries, 0 to 1895
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATAFLOW     1896 non-null   str
 1   LAST UPDATE  1896 non-null   str
 2   freq         1896 non-null   str
 3   indic_em     1896 non-null   str
 4   unit         1896 non-null   str
 5   age          1896 non-null   str
 6   sex          1896 non-null   str
 7   geo          1896 non-null   str
 8   TIME_PERIOD  1896 non-null   int64
 9   OBS_VALUE    1896 non-null   float64
 10  OBS_FLAG     102 non-null    str
 11  CONF_STATUS  0 non-null      float64
dtypes: float64(2), int64(1), str(9)
memory usage: 177.9 KB

In [6]:
print("Names of columns:", df.columns.tolist())

Names of columns: ['DATAFLOW', 'LAST UPDATE', 'freq', 'indic_em', 'unit', 'age', 'sex', 'geo', 'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS']

In [7]:
df.isna().sum()

DATAFLOW          0
LAST UPDATE       0
freq              0
indic_em          0
unit              0
age               0
sex               0
geo               0
TIME_PERIOD       0
OBS_VALUE         0
OBS_FLAG       1794
CONF_STATUS    1896
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.duplicated(
    subset=["geo", "TIME_PERIOD", "sex"],
    keep=False
).sum()

np.int64(0)

In [10]:
df.nunique()

DATAFLOW         1
LAST UPDATE      1
freq             1
indic_em         1
unit             1
age              1
sex              3
geo             38
TIME_PERIOD     21
OBS_VALUE      430
OBS_FLAG         2
CONF_STATUS      0
dtype: int64

In [11]:
df["sex"].value_counts(dropna=False)

sex
Females    632
Males      632
Total      632
Name: count, dtype: int64

In [12]:
df["geo"].value_counts(dropna=False)

geo
France                                       63
Sweden                                       63
Austria                                      51
Belgium                                      51
Bulgaria                                     51
Cyprus                                       51
Czechia                                      51
Germany                                      51
Denmark                                      51
Euro area – 20 countries (2023-2025)         51
Euro area – 21 countries (from 2026)         51
Estonia                                      51
Greece                                       51
Spain                                        51
European Union - 27 countries (from 2020)    51
Finland                                      51
Croatia                                      51
Hungary                                      51
Ireland                                      51
Italy                                        51
Lithuania                                    51
Luxembourg                                   51
Latvia                                       51
North Macedonia                              51
Malta                                        51
Netherlands                                  51
Norway                                       51
Poland                                       51
Portugal                                     51
Romania                                      51
Slovenia                                     51
Slovakia                                     51
Türkiye                                      51
Switzerland                                  48
Iceland                                      48
Serbia                                       48
Montenegro                                   30
Bosnia and Herzegovina                       15
Name: count, dtype: int64

In [13]:
df["OBS_FLAG"].value_counts(dropna=False)

OBS_FLAG
NaN    1794
b        72
d        30
Name: count, dtype: int64

In [14]:
df["OBS_FLAG"].unique()

<StringArray>
[nan, 'b', 'd']
Length: 3, dtype: str

In [15]:
df[df["OBS_FLAG"].notna()]

,DATAFLOW,LAST UPDATE,freq,indic_em,unit,age,sex,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
30,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Belgium,2017,63.6,b,NaN
40,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Bulgaria,2010,60.3,b,NaN
41,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Bulgaria,2011,59.4,b,NaN
49,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Bulgaria,2019,70.2,b,NaN
54,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Females,Bulgaria,2024,73.1,b,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1758,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Total,Poland,2010,62.2,b,NaN
1767,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Total,Poland,2019,72.6,b,NaN
1864,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Total,Slovakia,2011,66.8,b,NaN
1884,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Total,Türkiye,2014,53.2,b,NaN
1891,ESTAT:TESEM010(1.0),29/04/26 23:00:00,Annual,Total employment (resident population concept ...,Percentage of total population,From 20 to 64 years,Total,Türkiye,2021,53.9,b,NaN

In [18]:
df[["TIME_PERIOD", "OBS_VALUE"]].describe()

       TIME_PERIOD    OBS_VALUE
count  1896.000000  1896.000000
mean   2016.903481    71.014768
std       4.981832     9.999646
min    2005.000000    25.800000
25%    2013.000000    66.075000
50%    2017.000000    72.700000
75%    2021.000000    78.100000
max    2025.000000    91.100000

In [19]:
df[
    (df["OBS_VALUE"] < 0) |
    (df["OBS_VALUE"] > 100)
]

Empty DataFrame
Columns: [DATAFLOW, LAST UPDATE, freq, indic_em, unit, age, sex, geo, TIME_PERIOD, OBS_VALUE, OBS_FLAG, CONF_STATUS]
Index: []

In [20]:
year_coverage = (
    df.groupby("geo")
    .agg(
        first_year=("TIME_PERIOD", "min"),
        last_year=("TIME_PERIOD", "max"),
        number_of_years=("TIME_PERIOD", "nunique")
    )
    .sort_values("number_of_years")
)
year_coverage

,first_year,last_year,number_of_years
geo,,,
Bosnia and Herzegovina,2021,2025,5
Montenegro,2011,2020,10
Iceland,2009,2024,16
Serbia,2010,2025,16
Switzerland,2010,2025,16
Croatia,2009,2025,17
Belgium,2009,2025,17
Austria,2009,2025,17
Estonia,2009,2025,17
Euro area – 20 countries (2023-2025),2009,2025,17
Euro area – 21 countries (from 2026),2009,2025,17
European Union - 27 countries (from 2020),2009,2025,17
Finland,2009,2025,17
Cyprus,2009,2025,17
Czechia,2009,2025,17
Bulgaria,2009,2025,17
Malta,2009,2025,17
Greece,2009,2025,17
Germany,2009,2025,17
Hungary,2009,2025,17
Latvia,2009,2025,17
Lithuania,2009,2025,17
Ireland,2009,2025,17
Italy,2009,2025,17
Norway,2009,2025,17
Luxembourg,2009,2025,17
North Macedonia,2009,2025,17
Netherlands,2009,2025,17
Portugal,2009,2025,17
Poland,2009,2025,17
Romania,2009,2025,17
Denmark,2009,2025,17
Türkiye,2009,2025,17
Slovakia,2009,2025,17
Spain,2009,2025,17
Slovenia,2009,2025,17
France,2005,2025,21
Sweden,2005,2025,21

In [21]:
years_per_country=(
    df.groupby("geo")["TIME_PERIOD"]
    .apply(lambda years: sorted(years.unique()))
)
years_per_country

geo
Austria                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Belgium                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Bosnia and Herzegovina                                          [2021, 2022, 2023, 2024, 2025]
Bulgaria                                     [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Croatia                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Cyprus                                       [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Czechia                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Denmark                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Estonia                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Euro area – 20 countries (2023-2025)         [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Euro area – 21 countries (from 2026)         [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
European Union - 27 countries (from 2020)    [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Finland                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
France                                       [2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...
Germany                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Greece                                       [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Hungary                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Iceland                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Ireland                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Italy                                        [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Latvia                                       [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Lithuania                                    [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Luxembourg                                   [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Malta                                        [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Montenegro                                   [2011, 2012, 2013, 2014, 2015, 2016, 2017, 201...
Netherlands                                  [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
North Macedonia                              [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Norway                                       [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Poland                                       [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Portugal                                     [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Romania                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Serbia                                       [2010, 2011, 2012, 2013, 2014, 2015, 2016, 201...
Slovakia                                     [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Slovenia                                     [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Spain                                        [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Sweden                                       [2005, 2006, 2007, 2008, 2009, 2010, 2011, 201...
Switzerland                                  [2010, 2011, 2012, 2013, 2014, 2015, 2016, 201...
Türkiye                                      [2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...
Name: TIME_PERIOD, dtype: object

In [ ]:
flag_summary=(
    df[df["OBS_FLAG"].notna()]
    .groupby(["OBS_FLAG", "geo"])
    .size()
    .reset_index(name="number_of_rows")
)
flag_summary

   OBS_FLAG              geo  number_of_rows
0         b          Belgium               3
1         b         Bulgaria              12
2         b          Czechia               3
3         b          Denmark               9
4         b          Germany               9
5         b          Hungary               3
6         b          Iceland               3
7         b          Ireland               3
8         b            Italy               3
9         b       Luxembourg               3
10        b  North Macedonia               3
11        b           Poland               6
12        b         Slovakia               3
13        b      Switzerland               3
14        b          Türkiye               6
15        d           France              15
16        d            Spain              15

In [23]:
df.loc[
    df["OBS_FLAG"] == "d",
    ["geo", "TIME_PERIOD", "sex", "OBS_VALUE", "OBS_FLAG"]
].sort_values(["geo", "TIME_PERIOD", "sex"])

         geo  TIME_PERIOD      sex  OBS_VALUE OBS_FLAG
275   France         2021  Females       70.2        d
907   France         2021    Males       76.4        d
1539  France         2021    Total       73.2        d
276   France         2022  Females       71.2        d
908   France         2022    Males       77.0        d
1540  France         2022    Total       74.0        d
277   France         2023  Females       71.7        d
909   France         2023    Males       77.2        d
1541  France         2023    Total       74.4        d
278   France         2024  Females       72.2        d
910   France         2024    Males       78.1        d
1542  France         2024    Total       75.1        d
279   France         2025  Females       72.8        d
911   France         2025    Males       78.4        d
1543  France         2025    Total       75.5        d
220    Spain         2021  Females       62.1        d
852    Spain         2021    Males       72.9        d
1484   Spain         2021    Total       67.5        d
221    Spain         2022  Females       63.7        d
853    Spain         2022    Males       74.9        d
1485   Spain         2022    Total       69.3        d
222    Spain         2023  Females       65.4        d
854    Spain         2023    Males       75.7        d
1486   Spain         2023    Total       70.5        d
223    Spain         2024  Females       66.5        d
855    Spain         2024    Males       76.3        d
1487   Spain         2024    Total       71.4        d
224    Spain         2025  Females       67.6        d
856    Spain         2025    Males       77.1        d
1488   Spain         2025    Total       72.4        d

In [24]:
def find_missing_years(years):
    existing_years = set(years)
    expected_years = set(range(min(years), max(years) + 1))

    return sorted(expected_years - existing_years)


missing_years = (
    df.groupby("geo")["TIME_PERIOD"]
      .apply(find_missing_years)
)

missing_years[missing_years.apply(len) > 0]

Series([], Name: TIME_PERIOD, dtype: object)